micronaut:
  application:
    name: account-app
datasources:
  default:
    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1.'
    username: 'sa'
    password: ""
    driverClassName: 'org.h2.Driver'
jpa:
  default:
    packages-to-scan:
      - 'revolut.account.service.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations